version: "2.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: elasticsearch1
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
